#!/bin/bash

DOCKER_PLATFORMS=`echo $DOCKER_TAG | sed 's/^[^-]*-//'`
DOCKER_PLATFORMS=${DOCKER_PLATFORMS//-/\/}
TAGS=${DOCKER_TAG}
DOCKER_BASE=${DOCKER_REPO}

echo " =============== pwd"
pwd
ls -l

echo " =============== pwd ../"
ls -l ../

source ./multi-arch-docker-ci.sh

set -ex; multi_arch_docker::printvars; set +x
set -ex; multi_arch_docker::main; set +x
